### ISSUE TITLE
Database Schema 

### ISSUE THREAD

**Issue by AdamYLiang** [ezekielp/treebnb#2]
**Treehouses**
- [x] Consider including `price` for cos of TreeHouses
- [x] Consider adding a `lat` and `long` to represent coordinates for where the locations are. Will help out when you add Google Maps API into the mix. 

**Reviews**
- [x] Consider adding a `rating` 

Let me know if you have any questions or want to talk about these!

**Comment by ezekielp** [comment]
Thanks Adam, I think you're right, those were all oversights on my part. I added them to my schema.
